# Generated by Django 5.0.7 on 2024-07-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_adress_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='zip',
        ),
    ]
