# Generated by Django 5.0.7 on 2024-07-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_adress_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='peyment_status',
            new_name='payment_status',
        ),
    ]
